### ISSUE TITLE
Carthage support.

### ISSUE THREAD

**Issue by anupam57** [lightstep/lightstep-tracer-objc#47]
Hey,

If you could provide support for carthage as well, it would be great

Thanks
Anupam

**Comment by Igor-Palaguta** [comment]
+1

**Comment by Abeansits** [comment]
Any news on this? 
It's a very easy implementation: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework
All you basically have to do it share your scheme, build and tag your releases.

**Comment by austinlparker** [comment]
I'd be glad to add Carthage support, but I've tried everything I can find to get it to work in this repo and I'm getting nowhere fast - if anyone on this thread still wants it and could take a crack at it or give me some pointers, I'll merge it. :)

**Comment by osama10** [comment]
Do you guys have any plans for giving support for Carthage ?

**Comment by k28gupta** [comment]
@austinlparker  This PR https://github.com/lightstep/lightstep-tracer-objc/pull/51 does that. Please merge it if you can.

**Comment by mattrobmattrob** [comment]
**Edit:**
`github "lightstep/lightstep-tracer-objc" ~> 3.0` won't work until a new tag is pushed. And sorta incorrect still. This will work for now:
```
github "lightstep/lightstep-tracer-objc" "master"
```

**Original:**
@k28gupta, what version of Carthage and Xcode did you use to test this? At this point, I'm running into 👇 on Carthage (`v0.34.0`):
```bash
$ carthage update --platform iOS "lightstep-tracer-objc"
*** Checking out lightstep-tracer-objc at "3.2.14"
*** xcodebuild output can be found in /var/folders/7m/kxz71wv91x55476jh0wjf9sw0000gp/T/carthage-xcodebuild.llR9qS.log
*** Skipped building lightstep-tracer-objc due to the error:
Dependency "lightstep-tracer-objc" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/lightstep/lightstep-tracer-objc/issues/new
```
With the following in my `Cartfile`:
```
github "lightstep/lightstep-tracer-objc" ~> 3.0
```
Xcode and Carthage version info:
```
$ xcodebuild -version
Xcode 11.4
Build version 11E146

$ carthage version
0.34.0
```
